Sigespro.Web.Mvc/Models/Configuration/ProgramViewModel.cs
using Sigespro.Web.Mvc.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sigespro.Web.Mvc.Models.Configuration
{
    public class ProgramViewModel
    {
        public int IdPrograma { get; set; }
        
        [Display(Name = "ProgramName", ResourceType = typeof(Labels))]
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Messages))]
        public string NombrePrograma { get; set; }

        [Display(Name = "Description", ResourceType = typeof(Labels))]
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Messages))]
        public string Descripcion { get; set; }

        [Display(Name = "Active", ResourceType = typeof(Labels))]
        public bool Activo { get; set; }

        [Display(Name = "UserInsert", ResourceType = typeof(Labels))]
        public int IdUsuarioIns { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "DateInsert", ResourceType = typeof(Labels))]
        public DateTime FechaIns { get; set; }

        [Display(Name = "UserEdit", ResourceType = typeof(Labels))]
        public int? IdUsuarioUpd { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "DateEdit", ResourceType = typeof(Labels))]
        public DateTime? FechaUpd { get; set; }

        public bool Selected { get; set; }
    }

    public class RptProjectPrograms
    {
        public int IdPrograma { get; set; }
        
        public string NombrePrograma { get; set; }
        
        public string Descripcion { get; set; }
        
        public bool Activo { get; set; }
    }


}

Sigespro.Web.Mvc/Models/Project/Deliverables/DeliverableViewModel.cs
using Sigespro.Web.Mvc.Models.Budget;
using Sigespro.Web.Mvc.Models.Project.Tasks;
using Sigespro.Web.Mvc.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sigespro.Web.Mvc.Models.Project.Deliverables
{
    public class DeliverableViewModel
    {
        public int IdEntregable { get; set; }

        public int IdProyecto { get; set; }

        //public int? IdEntregableParent { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Description", ResourceType = typeof(Labels))]
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Messages))]
        public string Descripcion { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "StartDate", ResourceType = typeof(Labels))]
        public DateTime FechaInicio { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "EndDate", ResourceType = typeof(Labels))]
        public DateTime FechaFin { get; set; }

        public decimal DuracionEstimadaHoras { get; set; }

        public decimal DuracionEstimadaDias { get; set; }

        public decimal HorasDedicadas { get; set; }

        public int IdEstado { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Observations", ResourceType = typeof(Labels))]
        public string Nota { get; set; }

        public int PresupuestoID { get; set; }

        public decimal Presupuesto { get; set; }

        public int IdUsuarioIns { get; set; }

        public DateTime FechaIns { get; set; }

        public int? IdUsuarioUpd { get; set; }
        
        public DateTime? FechaUpd { get; set; }

        public List<TaskViewModel> Tasks { get; set; }

        public List<BudgetModel> FinancialBudget { get; set; }

        public List<PhysicalBudget> PhysicalBudget { get; set; }
    }
}

Sigespro.Web.Mvc/Models/Project/GoalsViewModel.cs
using Sigespro.Web.Mvc.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sigespro.Web.Mvc.Models.Project
{
    public class GoalsViewModel
    {
        public int IdObjetivo { get; set; }

        [Display(Name = "GoalType", ResourceType = typeof(Labels))]
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Messages))]
        public string TipoObjetivo { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Description", ResourceType = typeof(Labels))]
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Messages))]
        public string Descripcion { get; set; }

        public bool Activo { get; set; }
    }
}

Sigespro.Web.Mvc/Models/Project/ListProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sigespro.Web.Mvc.Models.Project
{
    public class ListProjectViewModel
    {
        public int IdProyecto { get; set; }

        public System.DateTime FechaInicio { get; set; }

        public System.DateTime FechaLimite { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:#,##0.#0}")]
        public string Presupuesto { get; set; }

        public string DescProyecto { get; set; }

        public string Justificacion { get; set; }

        public string GastoEstimado { get; set; }

        public string TituloProyecto { get; set; }

        public int HorasDedicadas { get; set; }

        public System.DateTime FechaFinEstimada { get; set; }

        public string PresupuestoActual { get; set; }

        public decimal DuracionEstimadaDias { get; set; }

        public decimal DuracionEstimadaHoras { get; set; }

        public int IdTipoProyecto { get; set; }

        public string TipoProyecto { get; set; }

        public int IdEstado { get; set; }

        public string Estado { get; set; }

        public int IdMoneda { get; set; }

        public string GrupoMeta { get; set; }
    }
}

Sigespro.Web.Mvc/Models/Project/Models.cs
using Sigespro.Web.Mvc.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sigespro.Web.Mvc.Models.Project
{
    public enum Tabs
    {
        GeneralInformation = 1,
        Goals = 2,
        Programs = 3,
        Managers = 4
    }

    public class ProgramProject
    {
        public int IdProgramaProyecto { get; set; }

        public int IdPrograma { get; set; }

        public int IdProyecto { get; set; }
    }

    public class BeneficiaryProject
    {
        public int IdProyecto { get; set; }

        public string TipoDestinatario { get; set; }

        public int? IdBeneficiario { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "TargetGroup", ResourceType = typeof(Labels))]
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Messages))]
        public string Descripcion { get; set; }
    }

    public class GoalsProject
    {
        public int IdProyectoObjetivo { get; set; }

        public int IdProyecto { get; set; }

        public int IdObjetivo { get; set; }

        public GoalsViewModel MstObjetivos { get; set; }
    }
    
    public class ProjectManager
    {
        public int IdProyectoResponsable { get; set; }

        public int IdProyecto { get; set; }

        public int? IdPersonal { get; set; }
    }
}

Sigespro.Web.Mvc/Models/Project/Tasks/TaskInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sigespro.Web.Mvc.Models.Project.Tasks
{
    public class TaskInfoViewModel: Entity.Custom.TaskInfo
    {  
        public HttpPostedFileBase[] files { get; set; }
    }
}

Sigespro.Web.Mvc/Controllers/Project/DeliverablesController.cs
using Common.Helpers;
using Common.Log;
using Newtonsoft.Json;
using Sigespro.Entity;
using Sigespro.Service.Pre;
using Sigespro.Service.Pro;
using Sigespro.Web.Mvc.Models.Project.Deliverables;
using Sigespro.Web.Mvc.Resources;
using Sigespro.Web.Mvc.Utilities.Attributes.Security;
using Sigespro.Web.Mvc.Utilities.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace Sigespro.Web.Mvc.Controllers.Project
{
    [RoutePrefix("Phase")]
    public class DeliverablesController : Controller
    {
        private readonly IUserSession _userSession;

        public DeliverableService Service { get; set; }

        public DeliverablesController()
        {
            Service = new DeliverableService();
            _userSession = new UserSession();
        }

        [AllowAnonymous]
        [Route("Add/{projectID}")]
        public ActionResult AddPartial(int projectID)
        {
            DateTime startDate = DateTime.Now, endDate = DateTime.Now;
            DeliverableViewModel model = new DeliverableViewModel();

            model.Nota = null;
            model.Descripcion = string.Empty;

            model.IdProyecto = projectID;

            model.FechaInicio = DateTime.Now;

            try
            {
                ProjectService prService = new ProjectService();
                var resultProject = prService.GetProjectById(projectID);

                // Se establece por defecto la fecha inicio del proyecto
                model.FechaInicio = resultProject.Data.FechaInicio;

                startDate = resultProject.Data.FechaInicio;
                endDate = resultProject.Data.FechaLimite;

                // Se obtiene el listado de entregables por id de proyecto
                var result = Service.GetDeliverablesByProjectID(projectID);

                if (result.MessageType == MessageType.INFO)
                {
                    if (result.Data != null)
                    {
                        if (result.Data.Count() > 0)
                        {
                            var last = result.Data.ToList().OrderByDescending(e => e.IdEntregable).FirstOrDefault();

                            // Si la fecha fin del último entregable es viernes, se le suman 3 día para el inicio del nuevo entregable
                            if (last.FechaFin.DayOfWeek == DayOfWeek.Friday)
                                model.FechaInicio = last.FechaFin.AddDays(3);
                            // Si es sabado se le agregan dos días
                            else if (last.FechaFin.DayOfWeek == DayOfWeek.Saturday)
                                model.FechaInicio = last.FechaFin.AddDays(2);
                            else // De lo contrario se le agrega un día
                                model.FechaInicio = last.FechaFin.AddDays(1);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.Log(MessageType.ERROR, ex, _userSession.Username, MethodBase.GetCurrentMethod().Name + " - " + GetType().Name, Request.UserHostAddress);
            }

            model.FechaFin = model.FechaInicio;

            ViewBag.StartDate = startDate;
            ViewBag.EndDate = endDate;
            ViewBag.Action = "Save";

            return PartialView("Partials/Deliverables/_addDeliverable", model);
        }

        [AllowAnonymous]
        [Route("Edit/{deliverableID}/{projectID}")]
        public ActionResult EditPartial(int deliverableID, int projectID)
        {
            DeliverableViewModel model = new DeliverableViewModel();
            DateTime startDate = DateTime.Now, endDate = DateTime.Now;

            try
            {
                var result = Service.GetDeliverableByID(deliverableID, projectID);

                if (result.MessageType == MessageType.INFO)
                {
                    model = new DeliverableViewModel
                    {
                        Descripcion = result.Data.Descripcion,
                        DuracionEstimadaDias = result.Data.DuracionEstimadaDias,
                        DuracionEstimadaHoras = result.Data.DuracionEstimadaHoras,
                        FechaFin = result.Data.FechaFin,
                        FechaInicio = result.Data.FechaInicio,
                        FechaIns = result.Data.FechaIns,
                        FechaUpd = result.Data.FechaUpd,
                        HorasDedicadas = result.Data.HorasDedicadas,
                        IdEntregable = result.Data.IdEntregable,
                        IdEstado = result.Data.IdEstado,
                        IdProyecto = result.Data.IdProyecto,
                        IdUsuarioIns = result.Data.IdUsuarioIns,
                        IdUsuarioUpd = result.Data.IdUsuarioUpd,
                        Nota = result.Data.Nota,
                        Presupuesto = result.Data.MstPresupuesto.FirstOrDefault().PresupuestoAsignado
                    };

                    ProjectService prService = new ProjectService();
                    var resultProject = prService.GetProjectById(projectID);

                    startDate = resultProject.Data.FechaInicio;
                    endDate = resultProject.Data.FechaLimite;
                }
            }
            catch (Exception ex)
            {
                Logger.Log(MessageType.ERROR, ex, _userSession.Username, MethodBase.GetCurrentMethod().Name + " - " + GetType().Name, Request.UserHostAddress);
            }

            ViewBag.StartDate = startDate;
            ViewBag.EndDate = endDate;
            ViewBag.Action = "Update";

            return PartialView("Partials/Deliverables/_addDeliverable", model);
        }

        [AjaxOnly]
        [HttpPost]
        [Route("Save")]
        [AllowAnonymous]
        public ActionResult Save(DeliverableViewModel model)
        {
            string message = string.Empty, status = "SUCCESS";

            try
            {
                if (ModelState.IsValid)
                {
                    model.IdEstado = 1;
                    model.IdUsuarioIns = _userSession.UserId;

                    string strSerialize = JsonConvert.SerializeObject(model);

                    var result = Service.InsertDeliverable(JsonConvert.DeserializeObject<Entity.Custom.Deliverable>(strSerialize));

                    if (result.MessageType != MessageType.SUCCESS)
                    {
                        message = result.Message;
                        status = result.MessageType.ToString();
                        Logger.Log(result.MessageType, result.DetailException, _userSession.Username,
                                MethodBase.GetCurrentMethod().Name + " - " + GetType().Name, Request.UserHostAddress);
                    }
                    else
                        message = string.Format(Messages.SaveSuccess, "fase de proyecto");
                }
            }
            catch (Exception ex)
            {
                Logger.Log(MessageType.ERROR, ex, _userSession.Username, MethodBase.GetCurrentMethod().Name + " - " + GetType().Name, Request.UserHostAddress);
            }

            return new JsonResult
            {
                Data = new { status, message },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        [AjaxOnly]
        [HttpPost]
        [Route("Update")]
        [AllowAnonymous]
        public ActionResult Update(DeliverableViewModel model)
        {
            string message = string.Empty, status = "SUCCESS";

            try
            {
                if (ModelState.IsValid)
                {
                    model.IdUsuarioUpd = _userSession.UserId;

                    string strSerialize = JsonConvert.SerializeObject(model);

                    var result = Service.UpdateDeliverable(JsonConvert.DeserializeObject<Entity.Custom.Deliverable>(strSerialize));

                    if (result.MessageType != MessageType.SUCCESS)
                    {
                        message = result.Message;
                        status = result.MessageType.ToString();
                        Logger.Log(result.MessageType, result.DetailException, _userSession.Username,
                                MethodBase.GetCurrentMethod().Name + " - " + GetType().Name, Request.UserHostAddress);
                    }
                    else
                        message = string.Format(Messages.UpdateSuccess, "fase de proyecto");
                }
            }
            catch (Exception ex)
            {
                Logger.Log(MessageType.ERROR, ex, _userSession.Username, MethodBase.GetCurrentMethod().Name + " - " + GetType().Name, Request.UserHostAddress);
            }

            return new JsonResult
            {
                Data = new { status, message },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        [AjaxOnly]
        [HttpPost]
        [AllowAnonymous]
        [Route("Delete/{deliverableID}/{projectID}")]
        public ActionResult Delete(int deliverableID, int projectID)
        {
            string message = string.Empty, status = "SUCCESS";

            try
            {
                var result = Service.DeleteDeliverable(deliverableID, projectID);

                if (result.MessageType != MessageType.SUCCESS)
                {
                    message = result.Message;
                    status = result.MessageType.ToString();
                    Logger.Log(result.MessageType, result.DetailException, _userSession.Username,
                            MethodBase.GetCurrentMethod().Name + " - " + GetType().Name, Request.UserHostAddress);
                }
                else
                    message = string.Format(Messages.DeleteSuccess, "fase de proyecto");
            }
            catch (Exception ex)
            {

Sigespro.Web.Mvc/Views/Shared/Partials/Project/_goals.cshtml
@using Sigespro.Web.Mvc.Resources;
@using Sigespro.Web.Mvc.Models.Project;

@model ProjectViewModel

@for (int i = 0; i < Model.DetProyectoObjetivos.Count; i++)
{
    <div class="row">
        <input type="hidden" name="@string.Format("DetProyectoObjetivos[{0}].IdProyectoObjetivo", i)" value="@Model.DetProyectoObjetivos[i].IdProyectoObjetivo" />
        <input type="hidden" name="@string.Format("DetProyectoObjetivos[{0}].IdObjetivo", i)" value="@Model.DetProyectoObjetivos[i].IdObjetivo" />

        <div class="col-md-2">
            <div class="form-group label-floating">
                @Html.LabelFor(model => model.DetProyectoObjetivos[i].MstObjetivos.TipoObjetivo, htmlAttributes: new { @class = "control-label" })
                @*@Html.DropDownListFor(model => model.DetProyectoObjetivos[i].MstObjetivos.TipoObjetivo, ViewBag.GoalsType as SelectList, new { @class = "form-control" }).IsDisabled(true)*@
                <select id="@string.Format("DetProyectoObjetivos_{0}__MstObjetivos_TipoObjetivo", i)" class="form-control"
                        name="@string.Format("DetProyectoObjetivos[{0}].MstObjetivos.TipoObjetivo", i)" disabled>
                    @foreach (var item in (ViewBag.GoalsType as SelectList))
                    {
                        if (item.Value == Model.DetProyectoObjetivos[i].MstObjetivos.TipoObjetivo)
                        {
                            <option value="@item.Value" selected="selected"> @item.Text </option>
                        }
                        else
                        {
                            <option value="@item.Value"> @item.Text </option>
                        }
                    }
                </select>
                @Html.HiddenFor(model => model.DetProyectoObjetivos[i].MstObjetivos.TipoObjetivo)
                @Html.ValidationMessageFor(model => model.DetProyectoObjetivos[i].MstObjetivos.TipoObjetivo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-9">
            <div class="form-group label-floating">
                @Html.LabelFor(model => model.DetProyectoObjetivos[i].MstObjetivos.Descripcion, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.DetProyectoObjetivos[i].MstObjetivos.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DetProyectoObjetivos[i].MstObjetivos.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-1">
            @if (Model.DetProyectoObjetivos.Count > 1)
            {
                <button type="button" class="btn btn-default" onclick="sigesproApp.project.deleteGoal(event)" data-action="@Url.Action("DeleteGoal", "Project", new { index = i })">
                    <b class="material-icons">delete</b>
                </button>
            }
        </div>
    </div>
    @Html.HiddenFor(model => model.DetProyectoObjetivos[i].MstObjetivos.IdObjetivo)
    @Html.HiddenFor(model => model.DetProyectoObjetivos[i].MstObjetivos.Activo)
}
<div class="row col-md-12 text-right">
    <button type="button" class="btn btn-raised btn-primary btn-fab" data-action="@Url.Action("AddGoal", "Project")"
             onclick="sigesproApp.project.addGoal(event)" title="@Labels.AddGoal">
        <i class="material-icons" style="pointer-events: none;">add</i>
    </button>
</div>
<div class="form-horizontal">
    <div class="form-group">
    </div>
</div>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-3"></div>
    <div class="col-md-5 text-right">
        <button type="button" class="btn btn-raised btn-primary" data-next="programs" data-next-title="@Labels.Programs"
                data-action="@Url.Action("LoadPrograms", "Project")" onclick="sigesproApp.project.next(event)" data-before="goals">
            <i class="material-icons" style="pointer-events: none;">navigate_next</i> @Labels.Next
        </button>
        <a href="@Url.Action("Index")" class="btn btn-raised btn-danger">
            <i class="material-icons" style="pointer-events: none;">cancel</i> @Labels.Cancel
        </a>
    </div>
</div>

Sigespro.Web.Mvc/Views/Shared/Partials/Project/_managers.cshtml
@using Common.Helpers;
@using Sigespro.Web.Mvc.Resources;
@using Sigespro.Web.Mvc.Models.Configuration;

@model IEnumerable<ListPersonalViewModel>

<div style="margin: -15px -30px;">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        @Labels.Name
                    </th>
                    <th>
                        @Labels.Program
                    </th>
                    <th>Cargo </th>
                    <th>
                        @Labels.State
                    </th>
                    @if (Model != null && Model.Count() > 0)
                    {
                        <th class="text-center">
                            <label>
                                <input type="checkbox" name="chk_All_Personal_" id="chk_All_Personal_" @Html.SetProperty(Model.All(p => p.Selected), "checked", "checked")
                                       data-action="@Url.Action("SelectPerson", "Project")" onclick="sigesproApp.project.checkAllPerson(event)" />  Seleccionar Todo
                            </label>
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                @{
                    if (Model == null || Model.Count() == 0)
                    {
                        <tr><td colspan="7" class="text-center">@string.Format(Messages.NoRecords, "de personal")</td></tr>
                    }
                    else
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NombrePrograma)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cargo)
                                </td>
                                <td>
                                    @(item.Activo ? Labels.Active : Labels.Inactive)
                                </td>
                                <td class="text-center">
                                    <input type="checkbox" name="chk_Personal_" id="chk_Personal_" @Html.SetProperty(item.Selected, "checked", "checked")
                                           data-item='@Html.Raw(Json.Encode(item))' data-action="@Url.Action("SelectPerson", "Project")"
                                           onclick="sigesproApp.project.checkPerson(event)" />
                                </td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<div class="form-horizontal">
    <div class="form-group">
    </div>
</div>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-3"></div>
    <div class="col-md-5 text-right">
        @if (Model.Any(p => p.Selected))
        {
            <button type="button" class="btn btn-raised btn-primary" onclick="sigesproApp.project.submitForm(event)">
                <i class="material-icons" style="pointer-events: none;">save</i> @Labels.Save
            </button>
        }
        else
        {
            <button type="button" class="btn btn-raised btn-primary" disabled>
                <i class="material-icons" style="pointer-events: none;">save</i> @Labels.Save
            </button>
        }

        <a href="@Url.Action("Index")" class="btn btn-raised btn-danger">
            <i class="material-icons" style="pointer-events: none;">cancel</i> @Labels.Cancel
        </a>
    </div>
</div>

Sigespro.Web.Mvc/Views/Shared/Partials/Project/_projectPlanning.cshtml
@model List<Sigespro.Web.Mvc.Models.Project.Deliverables.DeliverableViewModel>

@{
    Layout = "";

    if (Model != null && Model.Count > 0)
    {
        <div id="planning-table-content" class="planning-table-body">
        @foreach (var item in Model)
        {
            <div class="planning-table-row">
                <div class="planning-table-cell planning-table-cell-md-5 text-justify">
                    @item.Descripcion
                </div>
                <div class="planning-table-cell planning-table-cell-md-1">
                    @string.Format("{0:dd/MM/yyyy}", item.FechaInicio)
                </div>
                <div class="planning-table-cell planning-table-cell-md-1">
                    @string.Format("{0:dd/MM/yyyy}", item.FechaFin)
                </div>
                <div class="planning-table-cell planning-table-cell-md-1 text-right">
                    @string.Format("{0:#,##0.#0}", item.Presupuesto)
                </div>
                <div class="planning-table-cell planning-table-cell-md-2 text-center">
                    @if ((bool)ViewData["InPlanning"])
                    {
                        <i class="material-icons" onclick="sigesproApp.deliverables.addDeliverable(event)" title="Editar fase"
                        data-action="@Url.Action("EditPartial", "Deliverables", new {  deliverableID = item.IdEntregable, projectID = ViewBag.ProjectID })">edit</i>


                        <i class="material-icons" onclick="sigesproApp.deliverables.confirmDeleteDeliverable(event, '@ViewBag.ProjectID', '@Url.Action("PartialPlanning", "Project", new { projectId = ViewBag.ProjectID })')" title="Eliminar fase"
                           data-action="@Url.Action("Delete", "Deliverables", new { deliverableID = item.IdEntregable, projectID = ViewBag.ProjectID })">delete_forever</i>
                        <i class="material-icons" title="Agregar Tarea" onclick="sigesproApp.redirectTo('@Url.Action("Add", "Task", new { projectID = ViewBag.ProjectID, deliverableID = item.IdEntregable })')">add</i>
                        <i class="material-icons" title="Presupuestar" onclick="sigesproApp.redirectTo('@Url.Action("Budget", "Deliverables", new { deliverableID = item.IdEntregable, projectID = ViewBag.ProjectID })')">attach_money</i>
                    }
                </div>
            </div>
            if (item.Tasks != null && item.Tasks.Count > 0)
            {
                foreach (var task in item.Tasks)
                {
                    Html.RenderPartial("Partials/Task/_taskPlanning", task, new ViewDataDictionary { { "InPlanning", ViewData["InPlanning"] } });
                }
            }
        }
        </div>
    }
    else
    {
        <div id="empty-table" style="display: table-caption;position: absolute;width:100%"> 
                <div class="planning-table-cell colspan" style="text-align: center">
                    @Sigespro.Web.Mvc.Resources.Messages.ProjectNoTask
                </div> 
        </div>
    }
}